Ensure github-linguist compatibility
ocamllabs/vscode-ocaml-platform pull request #1659
Opened 2024-11-25 18:24 UTC by huwaireb

blocking https://github.com/github-linguist/linguist/pull/7126

There is one error remaining,

``
- Invalid regex in grammar: `source.ocaml.menhir` (in `syntaxes/menhir.json`) contains a malformed regex (regex "`(?<![[:word:]][[:space:]]*)\(`": lookbehind assertion is not fixed length (at offset 26))
``

in 

https://github.com/ocamllabs/vscode-ocaml-platform/blob/50bda9ffa384d026761b5179729707022565b754/syntaxes/menhir.json#L282.

p.s ensured formatting using biome.

2024-11-25 18:28 UTC, smorimoto commented
Could you take a look at this? @mnxn

2024-11-25 18:31 UTC, huwaireb commented
@mnxn, there is a slight issue with the linguist PR.

https://github.com/github-linguist/linguist/pull/7126#issuecomment-2470446614

could we have a `dune-all` grammar that includes all stanzas? Given the issue mentioned above.

2024-12-02 14:59 UTC, huwaireb commented on syntaxes/dune-all.json
Linguist doesn't support loading multiple grammars per language, so we have to include all the stanza patterns and the base one in a new grammar.

2024-12-03 05:29 UTC, mnxn commented on syntaxes/dune-all.json
This is fine.

2024-12-03 05:46 UTC, mnxn requested changes

2024-12-03 05:46 UTC, mnxn commented on syntaxes/menhir.json
> +          "begin": "(?<!\\w)\\(",
Previously, the regex would _not_ match either `a(b, c) = x` or `a (b, c) = x`. But now the second string matches.

I don't know what the ideal solution is here, but at the very least, both of the strings above should _not_ match.

2024-12-03 07:10 UTC, huwaireb commented on syntaxes/menhir.json
> +          "begin": "(?<!\\w)\\(",
It seems like it accepts this `(?<![[:word:]])(?<![[:space:]])\\(`, can we do this instead? Rubular parses it fine, i can't seem to get it to make the vsix to try it out.

2025-01-08 12:54 UTC, huwaireb commented on syntaxes/menhir.json
> +          "begin": "(?<!\\w)\\(",
hi @mnxn, sorry for the ping. but is there any way we can sort this out? This is the only remaining blocker afaik

2025-01-14 05:09 UTC, mnxn commented on syntaxes/menhir.json
> +          "begin": "(?<!\\w)\\(",
It doesn't look like that regex works. I think it might be fundamentally impossible to achieve the same behavior while staying fixed length.

I'm okay with relaxing the constraint a little bit and recognizing _only_ 0 or 1 spaces like the examples I posted above. This regex should accomplish that: `(?<![[:word:]]|[[:word:]][[:space:]])\(`


BTW: you can try the extension by opening the repo in VS Code and pressing the run button. No need to make a .vsix or even build the JS if you're just testing the syntaxes.

![image](https://github.com/user-attachments/assets/de51c0fb-cdf4-4cf7-b175-b9ff7845b6b6)

2025-01-17 21:19 UTC, huwaireb commented
bit of a problem now that i figured to test it ;c. It takes priority depending on order, and whilst some stanzas do work, the first included stanza e.g dune would be the only one that is highlighted correctly. The rest only partially. 

I probably could differentiate dune-project and dune by looking for (lang ...) at the top of the file, not sure about dune-workspace however. And that'd be a less painful way to address it, although not the best.

cc @mnxn

2025-01-21 07:54 UTC, mnxn commented
> bit of a problem now that i figured to test it ;c. It takes priority depending on order, and whilst some stanzas do work, the first included stanza e.g dune would be the only one that is highlighted correctly. The rest only partially.
> 
> I probably could differentiate dune-project and dune by looking for (lang ...) at the top of the file, not sure about dune-workspace however. And that'd be a less painful way to address it, although not the best.
> 
> cc @mnxn

Is there no way for linguist to use the filenames to determine which grammar is used?

2025-01-21 08:07 UTC, huwaireb commented
> Is there no way for linguist to use the filenames to determine which grammar is used?

that's what I tried initially, unfortunately each language can only use one grammar.

2025-04-11 12:37 UTC, closed without merging

2025-04-11 12:37 UTC, huwaireb commented
It doesn't look like there's a good way to do this without having a single grammar that supports all three dialects, so I'll close this.