Support `ocamllsp/nextHole` custom request
ocamllabs/vscode-ocaml-platform pull request #637
Opened 2021-06-14 10:53 UTC by ulugbekna

It is best to review all changes at once instead of commit-by-commit since there is some churn (but I don't yet squash to be able to revert some stuff if controversial)

Uploading Screen Recording 2021-06-14 at 3.52.24 PM.mov…

2021-06-14 19:28 UTC, mnxn requested changes

2021-06-14 19:28 UTC, mnxn commented on src/import.ml
> +let show_info fmt = show_message `Info fmt
These seem unnecessary. `show_message` is already a shortcut to the `Window.show...Message` functions.

2021-06-14 19:28 UTC, mnxn commented on src/extension_consts.ml
> +  let avail_when_editor_open ~expl cmd_name =
You might as well make this `available_when_editor_open`.

Omitting 4 characters doesn't help much with brevity here, instead it makes it harder to read.

2021-06-14 19:28 UTC, mnxn commented on package.json
> +        "key": "Alt+L"
I think this entry needs some `when` qualifiers since a comment says that the command is only available when a file is open.

2021-06-14 19:28 UTC, mnxn commented on src/import.ml
> +  let t_to_jsonoo t = t |> Position.t_to_js |> Jsonoo.t_of_js
`Jsonoo.t_of_js` isn't meant for encoding values.

You should use the `Jsonoo.Encode.*` functions.

2021-06-24 13:41 UTC, ulugbekna commented
Hi @mnxn, thanks for the review. I'm turning this PR to a draft, since it maybe a more lean on the ocamllsp side if we use a single new custom request to jump to prev/next typed hole (vs two custom requests that this PR would require in future). I tried to embed all of your comments in #643 :-)

2021-07-06 11:34 UTC, closed without merging